"""add_generated_material_table

Revision ID: 1dfa4707eb26
Revises: c17823771712
Create Date: 2026-04-06 14:44:22.421585

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # noqa: F401 — required for sqlmodel.sql.sqltypes.AutoString in autogenerated migrations

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1dfa4707eb26"
down_revision: Union[str, Sequence[str], None] = "c17823771712"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generatedmaterial",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("job_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bundle_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("resume_word_count", sa.Integer(), nullable=False),
        sa.Column("cover_letter_word_count", sa.Integer(), nullable=False),
        sa.Column("prep_brief_question_count", sa.Integer(), nullable=False),
        sa.Column("model_used", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("total_cost_usd", sa.Float(), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["normalizedjob.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_generatedmaterial_job_id"), "generatedmaterial", ["job_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_generatedmaterial_job_id"), table_name="generatedmaterial")
    op.drop_table("generatedmaterial")
    # ### end Alembic commands ###
