"""add is_stale to normalized_job

Revision ID: 85b46b272be9
Revises: e86913dc4de1
Create Date: 2026-04-05 09:08:48.730135

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # noqa: F401 — required for sqlmodel.sql.sqltypes.AutoString in autogenerated migrations

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85b46b272be9"
down_revision: Union[str, Sequence[str], None] = "e86913dc4de1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("normalizedjob", sa.Column("is_stale", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("normalizedjob", "is_stale")
    # ### end Alembic commands ###
