"""add_job_score_table

Revision ID: c17823771712
Revises: 85b46b272be9
Create Date: 2026-04-06 09:59:36.046078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 — required for sqlmodel.sql.sqltypes.AutoString in autogenerated migrations


# revision identifiers, used by Alembic.
revision: str = 'c17823771712'
down_revision: Union[str, Sequence[str], None] = '85b46b272be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobscore',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fit_score', sa.Float(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('strengths_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gaps_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('compensation_estimate', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reasoning', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_used', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scored_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['normalizedjob.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobscore_job_id'), 'jobscore', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobscore_job_id'), table_name='jobscore')
    op.drop_table('jobscore')
    # ### end Alembic commands ###
