"""initial schema

Revision ID: e86913dc4de1
Revises: 
Create Date: 2026-04-04 21:41:47.363699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e86913dc4de1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('normalizedjob',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_normalized', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('estimated_salary_min', sa.Integer(), nullable=True),
    sa.Column('estimated_salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requirements_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('raw_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalizedjob_company_slug'), 'normalizedjob', ['company_slug'], unique=False)
    op.create_index(op.f('ix_normalizedjob_description_hash'), 'normalizedjob', ['description_hash'], unique=False)
    op.create_index(op.f('ix_normalizedjob_source_url'), 'normalizedjob', ['source_url'], unique=True)
    op.create_index(op.f('ix_normalizedjob_title_normalized'), 'normalizedjob', ['title_normalized'], unique=False)
    op.create_table('decisionlog',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('decision_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('context_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['normalizedjob.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spendrecord',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('operation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['normalizedjob.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spendrecord_job_id'), 'spendrecord', ['job_id'], unique=False)
    op.create_table('statusevent',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['normalizedjob.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statusevent_job_id'), 'statusevent', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statusevent_job_id'), table_name='statusevent')
    op.drop_table('statusevent')
    op.drop_index(op.f('ix_spendrecord_job_id'), table_name='spendrecord')
    op.drop_table('spendrecord')
    op.drop_table('decisionlog')
    op.drop_index(op.f('ix_normalizedjob_title_normalized'), table_name='normalizedjob')
    op.drop_index(op.f('ix_normalizedjob_source_url'), table_name='normalizedjob')
    op.drop_index(op.f('ix_normalizedjob_description_hash'), table_name='normalizedjob')
    op.drop_index(op.f('ix_normalizedjob_company_slug'), table_name='normalizedjob')
    op.drop_table('normalizedjob')
    # ### end Alembic commands ###
